version: '3'

services:

  rehearsal:
    build: ./image
    container_name: rehearsal
    ports:
     - "5000:5000"
    volumes:
      - ./image/orquesta:/orquesta
      - ./image/web/src:/web/src
      - ./image/web/templates:/web/templates
